id: I3F8088EE
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-5ab7
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 12:28:30.368064+00:00
last_modified: 2023-09-26 12:28:30.368072+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W15659
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW15659
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་གི་འགྲེལ་བཤད་རྒྱལ་སྲས་ཡོན་ཏན་བུམ་བཟང་།
  languages:
  - bo
  author: དྷཱརྨ་ཀིརྟི་ཀུན་བཟང་བསོད་ནམས།
statistics:
  ocr_word_mean_confidence_index: 0.9964456152642452
  ocr_word_median_confidence_index: 1.0
bases:
  I1PD36347:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD36347
      total_pages: 898
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD36347.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9964456152642452
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
